name = "vbdesk-frontend"
type = "javascript"
account_id = ""  # Add your Cloudflare account ID
workers_dev = true
main = "dist/index.js"
compatibility_date = "2024-01-01"

[build]
cwd = "./app"
command = "npm run build"
watch_paths = ["./app/**/*.{ts,tsx,js,jsx,css}"]

[build.upload]
format = "modules"

[env.production]
name = "vbdesk-frontend-prod"
routes = [
  { pattern = "vbdesk.pages.dev", zone_name = "" }
]

[env.staging]
name = "vbdesk-frontend-staging"
